### ISSUE TITLE
Bug with ANSI escape sequence

### ISSUE THREAD

**Issue by syswraith** [wavetermdev/waveterm#116]
# Issue: 
- Erase screen sequence does not work 
- The second move cursor down sequence does not work
-  is not rendered properly

## How to reproduce:
1. Make a file named index.ans and put the content below inside
```
[2J[H[1m[3B[32m[6CWave term is awesome![0m[3B
```
2. Explanation
```
[2J = Erases entire screen
[H = Moves cursor to home position (0, 0)
[1m = Sets bold mode
[3B = Moves cursor down 3 lines
[32m = Sets color to green
[6C = Moves cursor right 6 columns
Wave term is awesome! = The text
[0m = Resets the color
[3B = Moves cursor down 3 lines
 = \u001B which is a standard escape character
```

3. `cat` the file: `cat index.ans`
4. Output from wave term:
![image](https://github.com/wavetermdev/waveterm/assets/77088155/74a3c100-e84a-459e-a1c2-1947a1536d59)
5. Output from system default terminal:
![image](https://github.com/wavetermdev/waveterm/assets/77088155/078e7c32-6989-4b73-b01f-62ef106244e0)

**Comment by sawka** [comment]
so it does look like it erased correctly and formatted the text right, the issue is that it didn't advance 3 lines down at the end?

so wave runs each command in its own pty, so the clear only runs in that pty for that command.

the reason why the last 3 lines didn't appear is that wave runs a special algorithm to try to decide how many lines of output to display in the terminal for each command -- it just looks for the last line that has text.  if the command is running it also takes into account the cursor position.

it is possible to control the size of the terminal for each command and disable the auto sizing behavior.  the interface is changing slightly for v0.5.1, so i'll update in a couple days if you're interested.

**Comment by syswraith** [comment]
Yes, that would be great.

**Comment by sawka** [comment]
well, good news / bad news.  so wave supports setting term options using the variable "wterm" passed to the command.  this is a wave specific variable (not a environment variable) so it is passed using a bracket syntax, e.g.:

[wterm=5x80] for x in 1 2 3 4 5 6 7 8 9 10; do echo $x; done

The idea is that will only allow the terminal to "grow" to 5 rows and 80 columns.  The default value for `wterm` is `MxM` which means set the rows/cols to the maximum (M) computed based on the size of your window.

The bad news is that I *thought* we supported a special "!" syntax to disable the auto sizing, e.g.:

`[wterm=5!x80] echo hello`

but, after testing, it looks like the flexrows option is not being disabled correctly.  So, I'll mark this issue as a bug, and will look into why this is not working as designed.
