### ISSUE TITLE
Command blocks: different color for results/error messages

### ISSUE THREAD

**Issue by CharlesNepote** [wavetermdev/waveterm#150]
When a past command blocks is opened, the visual difference between the command and the results/error messages is not sufficient. Picture below:
![image](https://github.com/wavetermdev/waveterm/assets/562352/689af20c-b3f8-4dac-8923-98688e65e7b2)

**Describe the solution you'd like**
* When there is an error, the message could be in a different color (tweakable with a setting, ideally).
* Also, it would be great to have some kind of visual difference between the command and the results. I guess the later should stay in their regular colors because some tools are already using colors. I have no idea to do it.

**Comment by sawka** [comment]
Thanks for submitting!  I see what you're saying.  For short commands it is easy to see the difference between command/results (because they go on the prompt line), but I see the problem in your screenshot for the multiline commands.

Trying to think of what could make sense for showing error status in a stronger way.  Maybe a subtle red background color for the whole line?

**Comment by CharlesNepote** [comment]
> Maybe a subtle red background color for the whole line?

Yes why not. I have no skills in UI design, sorry, I can't help you much :(

Could it be something like a CSS rule to make some tests?

**Comment by sawka** [comment]
Fixed in v0.7.0.  commands with non-zero exit codes are marked with a red background/outline.
