### ISSUE TITLE
[Request] Relax `user@host` form validation for connections

### ISSUE THREAD

**Issue by dljsjr** [wavetermdev/waveterm#184]
Based on the comments [here](https://github.com/wavetermdev/waveterm/issues/96), it seems that connections should already respect the configurations in the user's SSH Config File. If an SSH Config File has a `User` defined on a `Host`, then we don't need to include `user@` before the host in the connection string. However, the form validation in the Connections UI expects the username to be there.

There is already https://github.com/wavetermdev/waveterm/issues/95. But my understanding is that this existing issue is talking about pre-populating the connections UI.

I'm only advocating for not having form validation that expects all hosts to be prepended with `user@`.

In fact, based on https://github.com/wavetermdev/waveterm/issues/173, I would say that unless there's a verifiable threat model or security risk, there probably shouldn't be any form validation going on here at all outside of maybe sanitizing the input?

**Comment by sawka** [comment]
this makes sense.

my concern has been knowing what user should live on the other side of that connection and keeping them consistent.  because connections are persistent in Wave, it can be very jarring if the user changes out from underneath us.  (of course that can still happen if you use /etc/hosts or ssh config to override hosts names or user names).  same thing if the host changes out from underneath us.

my intuition on this is that we need to relax this, and move more to a model of connect and verify.  so on first connect we grab the *actual* username and some sort of host identifier and store that.  we can then have a flow or a warning if we connect again later and that username (or host identification, etc.) changes.

**Comment by sawka** [comment]
I tentatively targeted this to v0.6.0, but no guarantees until we get all of the work scoped and start working on it to see if any complications arise.

**Comment by sawka** [comment]
Had to remove the v0.6.0 target since it looks like this won't make this release.  The larger set of connection work will have to come in a future release.

**Comment by oneirocosm** [comment]
i have a fix for this, but it isn't in v0.7.0. provided everything works, it will be in the followup 0.7.1 release

**Comment by sawka** [comment]
this has been fixed as of v0.7.2
