### ISSUE TITLE
CTRL+R shorcut does not work properly (Bépo layout)

### ISSUE THREAD

**Issue by benjaminbellamy** [wavetermdev/waveterm#205]
**Describe the bug**
When using a [BÉPO](https://en.wikipedia.org/wiki/B%C3%89PO) keyboard, the search shortcut is not mapped on the R key but is mapped on the O key.

**To Reproduce**
1. Install the BÉPO keyboard layout
2. Type CTRL+R
3. Nothing happens
4. Type CTRL+O
5. Et voilà! (It works)

**Expected behavior**
CTRL+R should launch the search feature.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: tested on both MacOS Sonoma 14.2.1 and Linux Ubuntu 23.10 (both with BÉPO layout)
 - Version v0.5.3

**Additional context**
On the BÉPO layout, the O key is the fourth one, same as R on the QWERTY layout.

**Comment by sawka** [comment]
thanks for submitting and bringing this to our attention.  didn't realize there would be a difference for the bepo layout! we don't have a bepo keyboard to test with, but we can try to do some research to see why this is different and make sure we are using cross-language compatible keybindings.

**Comment by sawka** [comment]
Okay, progress.  In order to do our keyboard controls we've been using event.code (which counter-intuitively gives results like "KeyR").  However there is also event.key.  For QWERTY keyboards event.code and event.key are generally the same (for me both give "KeyR").  But, after reading the spec, I realize that event.code is a physical key location (indexed against QWERTY), and event.key is the actual character produced.

So, it seems that we should switch most of our keybindings to use event.key instead of event.code.  That should hopefully fix the issue you reported.

Here for reference: https://developer.chrome.com/blog/keyboardevent-keys-codes

**Comment by benjaminbellamy** [comment]
Just tested 0.6.1:
✅ it works, problem fixed!
