### ISSUE TITLE
Cannot set ollama as the 3rd party LLM

### ISSUE THREAD

**Issue by denizongar** [wavetermdev/waveterm#587]
**Describe the bug**
I can't seem to get ollama to work with Wave AI after following the steps described in the documentation.

**To Reproduce**
1. Make sure ollama is running and api works
2. Set the openaibaseurl and the openaimodel both from the frontend settings and via the CLI. 
3. Chat command returns an error about the telemetry being disabled, interactive mode does nothing.

**Desktop:**
 - OS: macOS 14.4.1
 - Client Version: 0.7.2

**Additional context**
- Telemetry is disabled and has never been on since install.
- I used the url mentioned in the [documentation](https://docs.waveterm.dev/features/supportedLLMs/ollama) and the [actual](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion) ollama api url, neither seems to work.
- Restarting wave resets the openaibaseurl back to `openai default` in the settings, clicking on the AI token input and pressing enter with the empty field changes the openaibaseurl back to the previously set url for some reason, however.
- Client info shows openaimodel is set to the desired model but doesn't include the openaibaseurl at all. openaiapitoken is listed but empty.

**Comment by gonzolively** [comment]
Hi @denizongar , 

Thank you for taking the time to submit an issue!

The issue was that we didn't properly ungate access to third-party LLM's (cloud-based  or local) when telemetry was set to "off". We have now whitelisted `openaibaseurl` so anytime that parameter set when telemetry is "off" local LLM's should work as configured. You can follow this fix [here](https://github.com/wavetermdev/waveterm/pull/590) and it should be live next release, which we hope is by EOW.

Your ancillary issues with the UI not properly showing parameters, and restarting Wave resetting parameters have also been fixed in this PR.
