### ISSUE TITLE
Loading content after changing renderer to "code" stucks

### ISSUE THREAD

**Issue by Zigu** [wavetermdev/waveterm#86]
**Describe the bug**
Reformatting of pom.xml to code stucks. (waited > 15mins)

**To Reproduce**
1. Go to a directory with a pom.xml (e.g. this one https://github.com/jeremylong/DependencyCheck/blob/main/pom.xml)
2. Open file with "less pom.xml"
3. Click on "line settings" icon
4. Change Renderer from "terminal" to "code"

**Expected behavior**
The file content will be rendered in colors.

**Screenshots**

<img width="1524" alt="Bildschirmfoto 2023-11-25 um 13 46 51" src="https://github.com/wavetermdev/waveterm/assets/402066/56b6999b-6c9f-45b9-abfe-719855802321">

**Desktop (please complete the following information):**
 - OS: MacOS x64
 - Version: v0.5.0

**Comment by sawka** [comment]
Ah, the problem is that your `less` command never terminates and the code renderer only renders content after the command has finished running.  So, you can either use a command that will just dump the whole file and terminate like `cat pom.xml`, or what I'd recommend is just running `codeedit pom.xml` or `codeview pom.xml` which will avoid any weird character / terminal encoding issues.
