### ISSUE TITLE
[Feature]: Support mouse edit mode in terminal

### ISSUE THREAD

**Issue by giovannicandido** [wavetermdev/waveterm#970]
### Feature description

I frequently reuse previously entered commands, and using the keyboard to navigate to a specific point in long-entered commands is painful when you experiment with a terminal that allows you to just click and edit like an IDE. Unfortunately this is not common. The only terminals I know that have this feature are Warp and the new beta terminal in IntelliJ idea.
More advanced features like multiple cursor editing are possible in this mode, but the ability to navigate the cursor with a click would make my life much more  productive in terminal 👌

**Comment by sawka** [comment]
For the current series we don't have plans to make Wave a "block" terminal.  Wave Legacy was based on blocks, but we've moved away from that model with the new v0.8 series.  I'd love to bring something like that back (but probably in a simpler form) at some point in the future, but I'm going to close this as "won't fix" for now since there are no immediate plans to do this.
